eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    eureka-service-url-poll-interval-seconds:
      defaultZone: http://localhost:8761/eureka
